---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-cuda-base
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/sclorg/s2i-base-container.git'
      ref: master
    contextDir: /base
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.rhel8
      from:
        kind: ImageStreamTag
        name: 's2i-cuda:11.8.0-cudnn8-devel-ubi8-core'
  output:
    to:
      kind: ImageStreamTag
      name: s2i-cuda:11.8.0-cudnn8-devel-ubi8
  triggers:
    - type: ImageChange
    - type: ConfigChange
