---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-cuda-base
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/edhat-na-ssa/demo-ocp-gpu.git'
    contextDir: /containers/s2i-cuda/ubi8
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: 'cuda:11.8.0-cudnn8-devel-ubi8'
  output:
    to:
      kind: ImageStreamTag
      name: s2i-cuda:11.8.0-cudnn8-devel-ubi8
  triggers:
    - type: ImageChange
    - type: ConfigChange
