---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-cuda-core
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/redhat-na-ssa/demo-ocp-gpu.git'
      ref: s2i-cuda
    contextDir: /containers/s2i-cuda
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: core/Dockerfile.rhel8
      from:
        kind: ImageStreamTag
        name: 'cuda:11.8.0-cudnn8-devel-ubi8'
  output:
    to:
      kind: ImageStreamTag
      name: s2i-cuda:11.8.0-cudnn8-devel-ubi8-core
  triggers:
    - type: ImageChange
    - type: ConfigChange
