---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: udi-cuda-addon
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/redhat-na-ssa/demo-ocp-gpu.git'
    contextDir: /containers/udi-cuda-addon
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: 'udi:ubi8-latest'
  output:
    to:
      kind: ImageStreamTag
      name: udi-cuda:addon
  triggers:
    - type: ImageChange
    - type: ConfigChange
