apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  demo: demo-ocp-gpu

resources:
  # setup devspaces operator
  - ../components/operators/devspaces/operator/overlays/stable
  - ../components/operators/devspaces/instance/overlays/timeout-12m

  # setup nfd operator
  - ../components/operators/nfd/operator/overlays/stable
  - ../components/operators/nfd/instance/overlays/only-nvidia

  # setup nvidia gpu operator
  - ../components/operators/gpu-operator-certified/operator/overlays/stable
  - ../components/operators/gpu-operator-certified/instance/overlays/time-slicing-4

  # setup tekton operator
  - ../components/operators/openshift-pipelines-operator-rh/operator/overlays/latest

  # setup namespaces
  - ../components/configs/namespaces/overlays/default
